"""
Django settings for sampleProject project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv(verbose=True)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR: Path = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: str | None = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG: bool = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS: list[str] = os.getenv(
    'ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition

INSTALLED_APPS: list[str] = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'aldjemy',
    'sample',  # add
]

MIDDLEWARE: list[str] = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]
# aws x-ray setting
if os.getenv('USE_AWS_XRAY', 'False') == 'True':
    MIDDLEWARE.extend([
        'aws_xray_sdk.ext.django.middleware.XRayMiddleware',
    ])
    INSTALLED_APPS.extend([
        'aws_xray_sdk.ext.django',
    ])
    XRAY_RECORDER = {
        'AUTO_INSTRUMENT': True,
        'AWS_XRAY_CONTEXT_MISSING': 'LOG_ERROR',
        'AWS_XRAY_DAEMON_ADDRESS': '127.0.0.1:2000',
        'AWS_XRAY_TRACING_NAME': 'SampleDjangoWebapps',
        'SAMPLING': False,
    }


ROOT_URLCONF: str = 'sampleProject.urls'

TEMPLATES: list[dict] = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION: str = 'sampleProject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
ALDJEMY_ENGINES: dict = {
    "mssql": 'mssql+pyodbc'
}

sqlite: dict = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
}

mssql: dict = {
    "ENGINE": "mssql",
    "NAME": os.getenv('MS_DB_NAME', ''),
    "USER": os.getenv('MS_DB_USER', ''),
    "PASSWORD": os.getenv('MS_DB_PASSWORD', ''),
    "HOST": os.getenv('MS_DB_HOST', 'localhost'),
    "PORT": os.getenv('MS_DB_PORT', '1433'),
    "OPTIONS": {
        "driver": os.getenv('MS_DB_DRIVER', 'ODBC Driver 18 for SQL Server'),
        "extra_params": os.getenv('MS_DB_EXTRA_PARAMS', ''),
    }
}


DATABASES: dict = {
    "default": sqlite if os.getenv('DB_ENGINE') == 'sqlite' else mssql
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS: list[dict] = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE: str = 'en-us'

TIME_ZONE: str = 'UTC'

USE_I18N: bool = True

USE_TZ: bool = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL: str = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD: str = 'django.db.models.BigAutoField'
